/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/resultados`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/admin/votaciones/[seccionId]`, params: Router.UnknownInputParams & { seccionId: string | number; } } | { pathname: `/votaciones/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/votar/[votacionId]`, params: Router.UnknownInputParams & { votacionId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/resultados`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/votaciones/[seccionId]`, params: Router.UnknownOutputParams & { seccionId: string; } } | { pathname: `/votaciones/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/votar/[votacionId]`, params: Router.UnknownOutputParams & { votacionId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | `/admin/resultados${`?${string}` | `#${string}` | ''}` | `/admin/usuarios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/admin/resultados`; params?: Router.UnknownInputParams; } | { pathname: `/admin/usuarios`; params?: Router.UnknownInputParams; } | `/admin/votaciones/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/votaciones/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/votar/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/admin/votaciones/[seccionId]`, params: Router.UnknownInputParams & { seccionId: string | number; } } | { pathname: `/votaciones/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/votar/[votacionId]`, params: Router.UnknownInputParams & { votacionId: string | number; } };
    }
  }
}
